name: Frontend Render Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build
      
      - name: Install Render CLI
        run: |
          curl -sfL https://install.render.com/cli.sh | bash -s -- -v=latest
        shell: bash

      - name: Deploy to Render
        run: |
          render login --api-key=${{ secrets.API_KEY }}
          render service deploy ${{ secrets.BACKEND_ID }}